Require handles to be null when providing the executor outputs
sociomantic-tsunami/dmxnet pull request #45
Opened 2017-12-08 15:39 UTC by jens-mueller-sociomantic

This change introduces the requirement to pass in output `NDArray`
instances with `null` handles. Previously, non-`null` handles were
allowed which can be surprising to the caller when freed under the hood.
Note, this is a breaking change. But it is better to force the caller to
be explicit about the `NDArray` instanced updated with an executor's
outputs. The documentation of the method is updated accordingly and the
`Throws` section is updated to include the case of non-`null handles.

2018-01-15 15:54 UTC, jens-mueller-sociomantic commented
Rebased.

2018-01-15 16:17 UTC, joseph-wakeling-sociomantic requested changes
A couple of small tweaks needed.  Also, this change needs release notes (needs to be added to the migration instructions).

2018-01-15 16:17 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Executor.d
> +        data).
Missing blank line between paragraphs?

2018-01-15 16:17 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Executor.d
> +import ocean.core.Verify;
This extra import appears unnecessary?

2018-01-15 17:45 UTC, joseph-wakeling-sociomantic commented
See: https://github.com/sociomantic-tsunami/neptune/blob/master/doc/library-contributor.rst for info on how to write release notes.  In this case you'll need to add a file like `relnotes/executor-outputs.migration.md`.

2018-01-15 17:46 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Executor.d
> +                                              .append(i);
As a note: it might make for easier-to-follow code if it reads something more like,

```D
throw mxnet_executor_exception
          .set("Output NDArray handle is non-null at index ")
          .append(i);
```

(not quite sure if that fits in 80 characters, but you get the idea).

2018-01-15 17:56 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Executor.d
> +                                              .append(i);
Alternatively, if the line is too long:

```D
throw mxnet_executor_exception
          .set("Output NDarray ")
          .append(i)
          .append(" has non-null handle!");
```

2018-01-16 12:37 UTC, jens-mueller-sociomantic commented on src/mxnet/Executor.d
> +import ocean.core.Verify;
Seems so. Don't know anymore how it ended up here. Maybe I had a version using `verify`.

2018-01-16 12:45 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Executor.d
> +import ocean.core.Verify;
Didn't the first draft work that way?

2018-01-16 13:01 UTC, jens-mueller-sociomantic commented
```diff
diff --git a/relnotes/executor-outputs.migration.md b/relnotes/executor-outputs.migration.md
new file mode 100644
index 0000000..b53a689
--- /dev/null
+++ b/relnotes/executor-outputs.migration.md
@@ -0,0 +1,12 @@
+## `NDarray` must have `null` handles when calling `Executor`'s `outputs`
+
+`mxnet.Executor`
+
+When obtaining the outputs of an `Executor` all `NDarray` instances passed to
+the method `outputs` must have a `null` handle. For migration you can call
+`freeHandle` on `NDArray` instances with non-`null` handles
+(`array.handle !is null`). This will release all data associated with the
+`NDArray` instance. This freeing used to happen implicitly under the hood when
+executing the `outputs` method. This migration requires this release of
+resources to be explicit in calling code. If the handles of the passed
+`NdArray` instances are `null` no changes need to be made.
diff --git a/src/mxnet/Executor.d b/src/mxnet/Executor.d
index bd2a816..b2b675e 100644
--- a/src/mxnet/Executor.d
+++ b/src/mxnet/Executor.d
@@ -25,7 +25,6 @@ import mxnet.Handle;
 import mxnet.NDArray;
 import mxnet.Symbol;

-import ocean.core.Verify;
 import ocean.text.util.StringC;
 import ocean.transition;
 import ocean.util.Convert;
@@ -406,6 +405,7 @@ public class Executor (T)
         of this method freeing the handles under the hood (because after
         freeing the caller may have no `NDArray`s instances able to access some
         data).
+
         Each time this method is called the handles of the passed instances are
         set. When calling this method more than once with different instances
         you end up with different `NDArray` instances with different handles
@@ -449,9 +449,9 @@ public class Executor (T)

             if (outputs[i].handle !is null)
             {
-                throw mxnet_executor_exception.set(
-                    "Output NDArray instance handle is non-null at index ")
-                                              .append(i);
+                throw mxnet_executor_exception
+                    .set("Output NDArray instance handle is non-null at index ")
+                    .append(i);
             }

             outputs[i].handle = handle;
```

2018-01-16 13:02 UTC, joseph-wakeling-sociomantic commented
Something looks wrong with the PR commits here ... ?

2018-01-16 13:03 UTC, jens-mueller-sociomantic commented
Rebased.

2018-01-16 13:04 UTC, jens-mueller-sociomantic commented
Should be good now.

2018-01-16 13:14 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +resources to be explicit in calling code. If the handles of the passed
`... to be explicit in calling code.`  -- I don't know if you maybe want to add an extra explanatory sentence here that the principle we are enforcing is that the user should be in control of the lifetime of resources, and the library should not make assumptions about what is valid ... ?

2018-01-16 13:15 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +`mxnet.Executor`
You can probably say `mxnet.Executor.outputs` here.

2018-01-16 13:15 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +## `NDarray` must have `null` handles when calling `Executor`'s `outputs`
`Executor.outputs` is probably a better way to denote this (briefer and clearer).

2018-01-16 13:20 UTC, jens-mueller-sociomantic commented on relnotes/executor-outputs.migration.md
> +`mxnet.Executor`
Even though the docs say `name.of.affected.module`?

2018-01-16 13:21 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +`mxnet.Executor`
OK, fair enough, leave it with the module name only.

2018-01-16 14:01 UTC, jens-mueller-sociomantic commented
Rebased and fixup.

2018-01-16 14:05 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +If the handles of the passed `NdArray` instances are `null` no changes need to
Typo: should be `NDArray` ... ?

2018-01-16 14:05 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +of resources while `dmxnet` states what it assumes about those.
I think you should be explicit here: `This reflects a design principle that the user should control ...`

2018-01-16 14:07 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +assumes about those.
Missing blank line between paragraphs.

2018-01-16 14:17 UTC, jens-mueller-sociomantic commented on relnotes/executor-outputs.migration.md
> +assumes about those.
Can't you have a newline without starting new paragraph? That's what I intended here. Something in between same paragraph and new paragraph.

2018-01-16 14:30 UTC, joseph-wakeling-sociomantic commented on relnotes/executor-outputs.migration.md
> +assumes about those.
No.  It's standard to put a blank line break (in particular, in the markup format we're using).

2018-01-16 15:28 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Executor.d
> +        freeing the caller may have no `NDArray`s instances able to access some
Typo: `NDArray` not `NDArray`s ... ?

2018-01-16 15:28 UTC, joseph-wakeling-sociomantic reviewed
Other than one small remaining typo, LGTM.  Can probably be squashed!

2018-01-16 15:32 UTC, jens-mueller-sociomantic commented
Squashed with

```diff
diff --git a/src/mxnet/Executor.d b/src/mxnet/Executor.d
index b2b675e..a952b61 100644
--- a/src/mxnet/Executor.d
+++ b/src/mxnet/Executor.d
@@ -403,7 +403,7 @@ public class Executor (T)
         The handles of the passed `NDArray` instances must be `null` (free the
         handles explicitly if needed). This is to avoid the surprising behavior
         of this method freeing the handles under the hood (because after
-        freeing the caller may have no `NDArray`s instances able to access some
+        freeing the caller may have no `NDArray` instances able to access some
         data).

         Each time this method is called the handles of the passed instances are
```

2018-01-16 15:34 UTC, joseph-wakeling-sociomantic approved these changes
LGTM.  I'll take in once CI passes.

2018-01-16 15:42 UTC, merged