Shutdown MXNet engine after running unittests
sociomantic-tsunami/dmxnet pull request #72
Opened 2018-06-22 12:22 UTC by jens-mueller-sociomantic

This change notifies MXNet to shutdown in the module destructor of
`mxnet.Handle`. This reduces the likelihood of crashes due to a race
happening after executing unittests. The race is likely to be caused by
dmxnet interacting with MXNet while MXNet is cleaning up at process exit
(see sociomantic-tsunami/dmxnet#66 for more details).

Note, that it does not seem to eliminate those crashes. It only seems to
reduce it because there still seems to be the possibility of a race
happening until MXNet actually shuts down. In so far, this is only a
measure to reduce the number of these crashes since after all they
happen at process exit anyway. In future, one should look into making
dmxnet always exit properly when running the unittests.

Part of sociomantic-tsunami/dmxnet#66.

2018-06-22 12:29 UTC, joseph-wakeling-sociomantic requested changes
Looks all right, just a few small tweaks/queries.

2018-06-22 12:29 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Handle.d
> +        notifyShutdown();
Is there a reason for putting it here instead of `mxnet.API`?  I'm not sure that my question in https://github.com/sociomantic-tsunami/dmxnet/issues/66#issuecomment-399384876 is really sufficient grounds to place it in `mxnet.Handle`.

2018-06-22 12:29 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Handle.d
> +// them
This could be module destructor doc.

2018-06-22 12:29 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Handle.d
> +version(UnitTest)
Minor style: `version (UnitTest)` (space after `version`)

2018-06-22 12:34 UTC, jens-mueller-sociomantic commented on src/mxnet/Handle.d
> +        notifyShutdown();
We can place it elsewhere. I think there are only organizational reason. One could put it into `mxnet.API` because after all the problem seems to be with using the MXNet API shuts down. On the other hand the problem seems to be specifically with handles which suggests to put it into `mxnet.Handle`. Either way is fine with me.

2018-06-22 12:37 UTC, jens-mueller-sociomantic commented on src/mxnet/Handle.d
> +// them
I think I would make it more public if it fixed the issue. Currently it's for me more like internal `FIXME` kind of doc. But I can change.

2018-06-22 13:58 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Handle.d
> +        notifyShutdown();
Let's keep it simple in terms of code changes and put it in `mxnet.API` for the time being.  The only reason for doing otherwise would be if it made a difference to the segfault occurring (and IIUC while it greatly reduces it, it doesn't entirely eliminate the segfaulting, no ... ?)

2018-06-22 14:00 UTC, joseph-wakeling-sociomantic commented on src/mxnet/Handle.d
> +// them
Fair enough.  Let's leave with just a comment then.

2018-06-22 14:09 UTC, jens-mueller-sociomantic commented on src/mxnet/Handle.d
> +// them
Hmm. Turned it into module documentation. It doesn't matter much. But I thought it also doesn't hurt to tell users about it.

2018-06-22 14:10 UTC, joseph-wakeling-sociomantic commented on src/mxnet/API.d
> +    Notifies the MXNet engine to shutdown after leaving `main` for unittests
Minor: if you're going to ddoc this I'd suggest putting the ddoc inside the `version (UnitTest)` block.

2018-06-22 14:11 UTC, joseph-wakeling-sociomantic commented on src/mxnet/API.d
> +       eliminate them.
Indentation inconsistency here.

2018-06-22 14:12 UTC, jens-mueller-sociomantic commented on src/mxnet/API.d
> +       eliminate them.
It's on purpose to align with the `NB`. I think it makes it stick out more. Meaning one won't miss it.

2018-06-22 14:14 UTC, joseph-wakeling-sociomantic commented on src/mxnet/API.d
> +       eliminate them.
You could always do:

```
Note:
    All the stuff you want noted
```

... which will highlight things in the generated ddoc too ;-)

2018-06-22 15:55 UTC, joseph-wakeling-sociomantic reviewed
This LGTM, just needs to be squashed.  (For the record with a small PR like this I think it's better to just make the tweaks in-place and post the diffs in comments, because then we don't have to worry about squashing once it's in a good state.)

2018-06-25 10:10 UTC, joseph-wakeling-sociomantic approved these changes

2018-06-25 10:10 UTC, joseph-wakeling-sociomantic commented
LGTM, we can take in once CI passes.

2018-06-25 10:23 UTC, merged