Convert dmxnet to be D2-only
sociomantic-tsunami/dmxnet pull request #88
Opened 2018-10-19 10:50 UTC by joseph-wakeling-sociomantic

This PR applies the D2 conversion changes generated by `make d2conv` and updates the ocean submodule to its corresponding `+d2` release.  The second patch cleans out inappropriate `(&this)` generated by the automated changes, so as to minimize overall PR diff to what matters.

`Build.mak` and `Config.mak` have been updated to drop special-casing for D1 and D2 builds and to hardcode `DVER := 2`, while `.neptune.yml` has been updated to mark the repo as D2-only.

The project `README` has been edited to remove sections on D1 => D2 conversion and to note that the library is D2 only.

Travis CI config has been updated to remove D1 builds and generation of autoconverted `+d2` releases.  Note that a consequence of this is that future D2 releases of dmxnet will have regular vX.y.z version tags, and not vX.y.z+d2.

CI builds have been added for vanilla upstream `dmd` to ensure that the library is not only compatible with `dmd-transitional`.

* submodules/ocean v4.2.10(ed0cb3f3)...v4.2.10+d2(402d4246) (1 commits)
  > Auto-convert to D2

2018-10-19 10:56 UTC, joseph-wakeling-sociomantic commented
Hmmm, interesting, `d1to2fix` is still being run.  Looks like there is something missing in setup.

2018-10-19 11:15 UTC, nemanja-boric-sociomantic commented
It seems that you're missing `.D2-ready` with `ONLY` as a content:

https://github.com/sociomantic-tsunami/beaver/blob/83d9759688974893916c8b8d6018bca1c1dd8ee4/lib/dlang.sh#L38-L44

2018-10-19 11:41 UTC, joseph-wakeling-sociomantic commented
Hah, I wondered if that was needed, but wasn't sure which of our systems cares.  I'll add.

2018-10-19 11:55 UTC, joseph-wakeling-sociomantic commented
Updated to set `D2_ONLY=1` in the travis CI environment:

```diff
diff --git a/.travis.yml b/.travis.yml
index 7c33d1e..72503d3 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,6 +25,7 @@ env:
         - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH)"
         - BEAVER_DOCKER_VARS="MXNET_ENGINE_TYPE"
         - DIST=xenial
+        - D2_ONLY=1
 
 # Basic config is inherited from the global scope
 jobs:
```

The 1st commit message has been tweaked a bit to reflect this.

2018-10-19 12:04 UTC, joseph-wakeling-sociomantic commented
Interesting that this doesn't work, I presume because beaver's `dlang.sh` does not actually check the value of this variable before overriding it based on the presence (or not) of `.D2-ready`.

2018-10-19 12:09 UTC, joseph-wakeling-sociomantic commented
Updated again to use `.D2-ready` instead of setting `D2_ONLY` in `.travis.yml`:

```diff
diff --git a/.D2-ready b/.D2-ready
new file mode 100644
index 0000000..bc8c7b4
--- /dev/null
+++ b/.D2-ready
@@ -0,0 +1 @@
+ONLY
diff --git a/.travis.yml b/.travis.yml
index 72503d3..7c33d1e 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,7 +25,6 @@ env:
         - PATH="$(git config -f .gitmodules submodule.beaver.path)/bin:$PATH)"
         - BEAVER_DOCKER_VARS="MXNET_ENGINE_TYPE"
         - DIST=xenial
-        - D2_ONLY=1
 
 # Basic config is inherited from the global scope
 jobs:
```

2018-10-19 12:49 UTC, joseph-wakeling-sociomantic commented
Well, this seems to work.  @nemanja-boric-sociomantic would you like to give a core-team eye on this, since you're here?  No worries if not.

2018-10-22 10:35 UTC, jens-mueller-sociomantic requested changes
Mostly asking for some clarification whether it is useful to use `enum`s, alignment of code and the mentioning of dropping `+d2` tags.

2018-10-22 10:35 UTC, jens-mueller-sociomantic commented on src/mxnet/NDArray.d
> +    static immutable bool isSupportedElementType =
I think `enum` would be better here than `static immutable`.

2018-10-22 10:35 UTC, jens-mueller-sociomantic commented on src/mxnet/NDArray.d
> +    static immutable bool isSupportedElementType =
This could be an `enum`.

2018-10-22 10:35 UTC, jens-mueller-sociomantic commented on src/mxnet/Util.d
> +    static immutable max_length = 1 + // optional minus sign
This could also be an `enum`. Also realigning the following comments would improve readability.

2018-10-22 10:35 UTC, jens-mueller-sociomantic commented on src/mxnet/Util.d
> +    static immutable format_string = "{:e8}";
Could also be an `enum`.

2018-10-22 10:35 UTC, jens-mueller-sociomantic commented on relnotes/d2-only.migration.md
> +now only build with a D2 compiler.
Should we mention here that from now there will be no `+d2` tags anymore. Could be surprising otherwise.

2018-10-22 12:27 UTC, joseph-wakeling-sociomantic commented on src/mxnet/NDArray.d
> +    static immutable bool isSupportedElementType =
For now we are not going to change anything in the autoconversion, apart from removing changes that really don't do anything (i.e. the superfluous `(&this)`).  We can do plenty of cleanup afterwards.

BTW there are some reasons to prefer `static immutable` over `enum`.  IIRC it relates to stack size and the number of individual copies that get instantiated.

2018-10-22 12:27 UTC, joseph-wakeling-sociomantic commented on relnotes/d2-only.migration.md
> +now only build with a D2 compiler.
Yes, sounds reasonable.  I'll update accordingly.

2018-10-22 14:15 UTC, joseph-wakeling-sociomantic commented
Updated to add a note on release tags to migration instructions:

```diff
diff --git a/relnotes/d2-only.migration.md b/relnotes/d2-only.migration.md
index 992715c..c2b73ec 100644
--- a/relnotes/d2-only.migration.md
+++ b/relnotes/d2-only.migration.md
@@ -3,3 +3,6 @@
 As of this release, dmxnet only supports D2 applications.  Its APIs have
 not changed, but its code has been converted from D1 to D2, and it will
 now only build with a D2 compiler.
+
+In consequence, D2 releases of dmxnet will now simply be tagged `vX.y.z`
+and not `vX.y.z+d2`.
```

2018-10-23 06:50 UTC, jens-mueller-sociomantic commented on src/mxnet/NDArray.d
> +    static immutable bool isSupportedElementType =
Yes, I was only pointing out this case because here we won't safe any stack size or instantiate less. I tried to only point out the cases where those arguments should not apply. But let's leave this for later.

2018-10-23 06:53 UTC, jens-mueller-sociomantic submitted a review, later dismissed
LGTM.

2018-10-23 12:49 UTC, joseph-wakeling-sociomantic commented
I had to force-push to re-trigger CI hooks; since I needed to do this anyway I took the opportunity to tweak the release notes slightly:

```diff
diff --git a/relnotes/d2-only.migration.md b/relnotes/d2-only.migration.md
index c2b73ec..0542e04 100644
--- a/relnotes/d2-only.migration.md
+++ b/relnotes/d2-only.migration.md
@@ -4,5 +4,5 @@ As of this release, dmxnet only supports D2 applications.  Its APIs have
 not changed, but its code has been converted from D1 to D2, and it will
 now only build with a D2 compiler.
 
-In consequence, D2 releases of dmxnet will now simply be tagged `vX.y.z`
-and not `vX.y.z+d2`.
+In consequence, D2 releases of dmxnet (the only kind from here on out!)
+will now simply be tagged `vX.y.z` and not `vX.y.z+d2`.
```

2018-10-24 10:00 UTC, jens-mueller-sociomantic approved these changes

2018-10-24 10:09 UTC, merged